export const events = [
  {
    id: 1,
    status: 'ongoing',
    name: 'Runn',
    date: '2023-12-01',
    time: '10:00 AM',
    venue: 'Ground',
    fee: 'FREE',
    organizingClub: 'KIET',
    description: 'Runn is a one stop event for all sports',
  },
  {
    id: 2,
    status: 'ongoing',
    name: 'Welcome To Linux',
    date: '2023-12-05',
    time: '2:00 PM',
    venue: 'E-512',
    fee: 'FREE',
    organizingClub: 'FOSSCU',
    description: 'This event aimed to kick start linux in our college',
  },
  {
    id: 3,
    status: 'upcoming',
    name: 'GDSC Recruitment',
    date: '2023-12-10',
    time: '5:00 PM',
    venue: 'E block 5th floor',
    fee: 'FREE',
    organizingClub: 'GDSC',
    description: 'Recruitment for 1st and 2nd year',
  },
  {
    id: 4,
    status: 'upcoming',
    name: 'Git & GitHub',
    date: '2023-12-15',
    time: '5:00 AM',
    venue: 'FOSSCU cabin',
    fee: 'FREE',
    organizingClub: 'FOSSCU',
    description: 'Get started with Git and Github',
  },
  {
    id: 5,
    status: 'ended',
    name: 'Pixel Playground',
    date: '2023-11-25',
    time: '5:00 PM',
    venue: 'online',
    fee: 'FREE',
    organizingClub: 'GDSC',
    description: 'Show your creativeness here',
  },
  {
    id: 6,
    status: 'ended',
    name: 'SWOC',
    date: '2023-11-01',
    time: '5:00 PM',
    venue: 'CRPC Hall',
    fee: 'FREE',
    organizingClub: 'Innogeeks',
    description: 'Love open source contribution join us',
  },
  {
    id: 8,
    status: 'ended',
    name: "FOSSCONF'23",
    date: '2023-11-26',
    time: '10:00 AM',
    venue: 'IIIT Delhi',
    fee: '250rs',
    organizingClub: 'FOSSCU',
    description: 'An open source event',
  },
];